"""
BioForge Protocol Card Generator
---------------------------------
Generates a structured optimization protocol card for any validated
waste-to-value bioprocess. Output is a printable, reproducible document
that any U.S. lab or manufacturer can implement independently.
"""

import pandas as pd
from datetime import datetime


class ProtocolCard:
    """Generates BioForge optimization protocol cards."""

    def __init__(
        self,
        waste_stream: str,
        target_product: str,
        organism: str,
        conditions: dict,
        fixed_conditions: dict,
        predicted_yield: float,
        baseline_yield: float,
        model_name: str,
        r2: float,
        rmse: float,
        sensitivity_df: pd.DataFrame,
    ):
        self.waste_stream = waste_stream
        self.target_product = target_product
        self.organism = organism
        self.conditions = conditions
        self.fixed_conditions = fixed_conditions
        self.predicted_yield = predicted_yield
        self.baseline_yield = baseline_yield
        self.improvement_pct = round(
            (predicted_yield - baseline_yield) / baseline_yield * 100, 1
        )
        self.model_name = model_name
        self.r2 = r2
        self.rmse = rmse
        self.sensitivity_df = sensitivity_df
        self.generated_at = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

    def to_text(self) -> str:
        """Return a plain-text protocol card."""
        lines = [
            "=" * 70,
            "  BIOFORGE OPTIMIZATION PROTOCOL CARD",
            "  Generated by BioForge v0.1 | Okedi, O.M. | " + self.generated_at,
            "=" * 70,
            "",
            f"  Waste Stream     : {self.waste_stream}",
            f"  Target Product   : {self.target_product}",
            f"  Production Org.  : {self.organism}",
            "",
            "-" * 70,
            "  OPTIMAL PROCESS CONDITIONS (DOE + ML Optimized)",
            "-" * 70,
        ]

        for factor, value in self.conditions.items():
            lines.append(f"  {factor:<35}: {value}")

        lines += [
            "",
            "-" * 70,
            "  FIXED FERMENTATION CONDITIONS",
            "-" * 70,
        ]
        for param, value in self.fixed_conditions.items():
            lines.append(f"  {param:<35}: {value}")

        lines += [
            "",
            "-" * 70,
            "  PREDICTED PERFORMANCE",
            "-" * 70,
            f"  Baseline yield (no stimulants)  : {self.baseline_yield:.2f} g/l",
            f"  Optimized yield (BioForge)      : {self.predicted_yield:.2f} g/l",
            f"  Improvement over baseline       : +{self.improvement_pct}%",
            "",
            "-" * 70,
            "  MODEL VALIDATION",
            "-" * 70,
            f"  Best Model       : {self.model_name}",
            f"  R²               : {self.r2:.5f}",
            f"  RMSE             : {self.rmse:.5f} g/l",
            "",
            "-" * 70,
            "  FACTOR SENSITIVITY RANKING (Permutation Importance)",
            "-" * 70,
        ]

        for _, row in self.sensitivity_df.iterrows():
            lines.append(
                f"  #{int(row['Rank'])}  {row['Factor']:<30}: {row['Importance (%)']:.2f}%"
            )

        lines += [
            "",
            "-" * 70,
            "  REPRODUCIBILITY NOTE",
            "-" * 70,
            "  This protocol was generated using BioForge, an open-source",
            "  DOE + ML optimization framework. All code, data, and model",
            "  parameters are publicly available at:",
            "  https://github.com/ogaga-ai/BioForge",
            "",
            "  Any U.S. research institution or manufacturer may apply this",
            "  protocol to their waste stream without requiring access to the",
            "  original investigator or laboratory.",
            "=" * 70,
        ]

        return "\n".join(lines)

    def save(self, path: str):
        """Save protocol card to a text file."""
        with open(path, 'w') as f:
            f.write(self.to_text())
        print(f"Protocol card saved to: {path}")
